version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - custom
  
  angular:
    build: ../../web/ng2app
    restart: unless-stopped
    ports: 
    - "4200:4200"
    command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - custom

  db:
    container_name: "db"
    build: ./docker/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
        - custom

  admin:
    build: ./docker/adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - custom
      
networks:
  custom:
    driver: bridge